// don't use this one //
//		      //
CREATE TABLE IF NOT EXISTS drinks(
  drink_id SERIAL PRIMARY KEY,
  drink_name VARCHAR(45) NOT NULL,       /* Name of the drink */
  category INT[] NULL,
  quantity_one FLOAT NULL,   /* quantity of ingredient */
  ingredient_one VARCHAR(45) NULL, /* ingredient */
  quantity_two FLOAT NULL,   /* quantity of ingredient */
  ingredient_two VARCHAR(45) NULL, /* ingredient */
  quantity_three FLOAT NULL,   /* quantity of ingredient */
  ingredient_three VARCHAR(45) NULL, /* ingredient */
  quantity_four FLOAT NULL,   /* quantity of ingredient */
  ingredient_four VARCHAR(45) NULL, /* ingredient */
  quantity_five FLOAT NULL,   /* quantity of ingredient */
  ingredient_five VARCHAR(45) NULL, /* ingredient */
  quantity_six FLOAT NULL,   /* quantity of ingredient */
  ingredient_six VARCHAR(45) NULL, /* ingredient */
  quantity_seven FLOAT NULL,   /* quantity of ingredient */
  ingredient_seven VARCHAR(45) NULL, /* ingredient */
  quantity_eight FLOAT NULL,   /* quantity of ingredient */
  ingredient_eight VARCHAR(45) NULL, /* ingredient */
  quantity_nine FLOAT NULL,   /* quantity of ingredient */
  ingredient_nine VARCHAR(45) NULL, /* ingredient */
  quantity_ten FLOAT NULL,   /* quantity of ingredient */
  ingredient_ten VARCHAR(45) NULL /* ingredient */
);

CREATE TABLE IF NOT EXISTS categories(
  id SERIAL PRIMARY KEY,       /* Unique identifier for each player (it's possible multiple players have the same name/similiar information) */
  name VARCHAR(50) NOT NULL,   /* The player's first & last name */
  description TEXT NULL,             /* FSH - Freshman, SPH - Sophomore, JNR - Junior, SNR - Senior */
  img_src VARCHAR(200)         /* This is a file path (absolute or relative), that locates the drink image */
);



DROP TABLE drinks;

CREATE TABLE IF NOT EXISTS drinks(
   drink_id SERIAL PRIMARY KEY
  ,drink_name        VARCHAR(26) NOT NULL
  ,category          INT NULL
  ,quantiry_one_oz   FLOAT NULL
  ,ingredient_one    VARCHAR(23) NULL
  ,quantity_two_oz   FLOAT NULL 
  ,ingredient_two    VARCHAR(25) NULL
  ,quantity_three_oz FLOAT NULL
  ,ingredient_three  VARCHAR(23) NULL
  ,quantity_four_oz  FLOAT NULL
  ,ingredient_four   VARCHAR(19) NULL
  ,quantity_five_oz  FLOAT NULL
  ,ingredient_five   VARCHAR(19) NULL
  ,quantity_six_oz   FLOAT NULL
  ,ingredient_six    VARCHAR(16) NULL
  ,quantity_seven_oz FLOAT NULL
  ,ingredient_seven  VARCHAR(16) NULL
  ,quantity_eight_oz FLOAT NULL
  ,ingredient_eight  VARCHAR(9) NULL
  ,quantity_nine_oz  FLOAT NULL
  ,ingredient_nine   VARCHAR(17) NULL
);


INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Alabama_Slammer',NULL,1,'Southern Comfort',1,'Amaretto',1,'Sloe_Gin',2,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Americano',NULL,1.50,'Campari',1.50,'Sweet_Vermouth',1.50,'Soda_Water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Anejo_Highball',NULL,1.50,'Rum',0.50,'Orange_Cruacao',0.50,'Lime_Juice',2,'Ginger_Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Bacardi_Cocktail',NULL,2,'Light_Rum',0.50,'Lime_Juice',0.50,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Bay_Breeze',NULL,2,'Vodka',3,'Cranberry_Juice',3,'Pineapple_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Bees_Knees',NULL,2,'Gin',0.75,'Honey_Syrup',0.50,'Lemon_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Campari_and_Soda',NULL,2,'Campary',6,'Soda_Water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Cantarito',NULL,1.50,'Tequila',0.50,'Lime_Juice',0.50,'Lemon_Juice',0.50,'Orange_Juice',4,'Grapefruit_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Cape_Cod',NULL,3,'Cranberry_Juice',2,'Vodka',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Dark_and_Stormy',NULL,0.50,'Dark_Rum',3,'Ginger_Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Dry_Martini',NULL,2.50,'Gin',0.50,'Dry_Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Dubonnet_Cocktail',NULL,1.50,'Gin',0.75,'Dubonnet_Rogue',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Easter_Bunny',NULL,1.50,'Creme_De_Cacao',0.50,'Vodka',0.16,'Chocolate_Syruop',0.16,'Cherry_Brandy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Electric_Iced_Tea',NULL,0.50,'Vodka',0.50,'Light_Rum',0.50,'Tequila',0.50,'Gin',0.50,'Blue_Curacao',1,'Sour_Mix',1,'Lemon_Lime_Soda',NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('El_Diablo',NULL,1.50,'Reposado_tequila',0.50,'Creme_De_Cassis',0.50,'Lime_Juice',6,'Ginger Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('French_75',NULL,1.50,'Gin',0.16,'Syrup',0.50,'Fresh_Lemon_Juice',4,'Champagne',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('French_Pear_Martini',NULL,1.50,'Elderflower_Liqueur',1.50,'Pear_Vodka',1,'Champagne',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Friar_Tuck_Cocktails',NULL,1,'Frangelico',1,'Dark_Creme_De_Cacao',2,'Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Gibson_Cocktail',NULL,2.50,'Gin',0.50,'Dry_Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Gimlet',NULL,2,'Gin',0.75,'Lime_Cordial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Gir_Scout_Cookie_Cocktail',NULL,0.50,'Coffee-Liqueur',0.50,'Irish_Cream_Liqueur',0.50,'Peppermint_Schnapps',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Hairy_Navel_Cocktail',NULL,1,'Vodka',1,'Peach_Schnapps',8,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Harvey Wallbanger Cocktail',NULL,1.50,'Vodka',4,'Orange_Juice',0.50,'Galliano_L’Autentico',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Hawaiian_Iced_tea',NULL,0.50,'Vodka',0.50,'Light_Rum',0.50,'Tequila',0.50,'Gin',0.50,'Triple_Sec',1,'Sour_Mix',2,'Pineapple_Juice',NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Irish_Slammer',NULL,0.75,'Irish_Cream_Liqueur',0.75,'Irish_Whiskey',8,'Guinness',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Irish_Coffee',NULL,1.50,'Brown_Sugar',4,'Coffee',1.50,'Irish_Whiskey',1,'Heavy_Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Irish_Cactus',NULL,2,'Irish_Cream_Liqueur',1,'Tequila',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Jack_O_Lantern',NULL,1.50,'Cognac',0.50,'Orange_Liqueur',1,'Orange_Juice',2,'Ginger_Ale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Jack_Rose',NULL,2.50,'AppleJack',0.75,'Lemon_Juice',0.50,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Jalisco_High_Tea_Tequila',NULL,1.50,'Tequila',1.50,'Lemon_Verbena_Tea',0.25,'Cherry_Liqueur',0.50,'Simple_Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Kentucky_Coffee',NULL,1,'Bourbon_Whiskey',0.50,'Honey_Liqueur',6,'Hot_Coffee',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Key_Lime_Pie_Martini',NULL,1.50,'Vanila_Vodka',0.50,'Triple_Sec_Orange_Liqueur',1,'Pineapple_Juice',0.50,'Lime_Cordial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('KnickerBocker',NULL,2.50,'Rum',0.50,'Raspberry-Syrup',1,'Orange_Curacao',0.50,'Lime_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Lavender_Martini',NULL,2,'gin',0.50,'Dry_Vermouth',0.50,'Lavender_Simple _Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Long_Beached_Iced_Tea',NULL,0.50,'Vodka',0.50,'Light_Rum',0.50,'Tequila',0.50,'Gin',0.50,'Triple_Sec',1,'Sour_Mix',2,'Cranberrry_Juice',NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Lady_Liberty',NULL,2,'Rum',1,'Orgeat_syrup',0.25,'Maraschino_Liqueur',0.25,'Green_Chartreuse',1,'Lime_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Madras',NULL,1.50,'Vodka',3,'Cranberry_Juice',1,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Mai_Tai',NULL,1,'Rhum_Agricole',1,'Dark_Rum',1,'Lime_Juice',0.50,'Orange_Curacao',0.50,'Orgeat_syrup',0.25,'Simple_Syrup',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Metropolitan',NULL,2,'Brandy',1,'Sweet_Vermouth',0.10,'Simple_Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Napoleon',NULL,2,'Gin',0.50,'Orange_Liqueur',0.50,'Debonnet_Rouge',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Nevada_Cocktail',NULL,1.50,'Light_Rum',1.50,'Grapefruit_Juice',1,'Lime_Juice',0.33,'Superfine_Sugar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Nightcap',NULL,1,'Brandy',1,'Anisettem1',1.00,'Curacao_Liqueur',1.00,'Egg_Yolk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Orange_Blossom_Cocktail',NULL,0.75,'Gin',0.75,'Sweet_Vermouth',0.75,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Orange_Martini',NULL,2,'Gin',0.50,'Triple_sec',0.50,'Dry_Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('O_Sole_Mio',NULL,1.50,'Antica-Orange_and_Mango',0.50,'Lemon_Juice',2,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Painkiller',NULL,2,'Rum',4,'Pineapple_Juice',1,'Orange_Juice',1,'Cream_of_Coconut',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Paloma',NULL,2,'tequila',0.33,'Lime_juice',4,'Grapefruit_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Peppermint_Patty',NULL,2,'Chocolate_Vodka',0.50,'Peppermint_Schnapps',0.75,'Cream_Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Raspberry_Gimlet_Shooter',NULL,1.50,'Vodka',0.50,'Lime_Juice',0.03,'Black_Raspberry_Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Red_Beer',NULL,2,'Tomato_Juice',12,'Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Robert_Burns',NULL,2,'Scotch_Whisky',0.75,'Sweet_Vermouth',0.03,'Orange_bitters',0.03,'Absinthe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Sake_Martini',NULL,2.50,'Gin',0.50,'Sake',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Shirley_Temple',NULL,0.25,'Grenadine',3,'Lemon-Lime_Soda',3.00,'Ginger_Ale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Scoth_Sour',NULL,1.50,'Scotch_Whiskey',0.75,'Lemon_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Tequini',NULL,2.50,'Tequila',0.50,'Dry_Vermouth',0.03,'Angousta_Bitters',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Talking_Monkey',NULL,1,'Chocolate_Vodka',0.03,'Espresso_Vodka',1,'Banana_Liqueur',0.03,'Coffee_Liqueur',1,'Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Tornado',NULL,1,'Whiskey',1,'Vodka',1,'Rum',1,'Tequila',2,'Cola',0.06,'Sugar',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Vermouth_Cassis',NULL,2.50,'Dry_Vermouth',0.75,'Creme_De_Cassis',3,'Club_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Vieux_Carre',NULL,0.75,'Rye_Whiskey',0.75,'Cognac',0.75,'Sweet_Vermouth',0.50,'Benedictine_Liqueur',.06,'Peychaud’s_bitters',.06,'Aromatic_Bitters',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Vampires_Kiss',NULL,1.50,'Melon_Liqueur',1,'Orange_Vodk',2,'Pineapple_Juice',0.50,'Cream',0.03,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Waldorf',NULL,2,'Rye_Whiskey',0.75,'Sweet_Vermouth',0.25,'Absinthe',0.06,'Bitters',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Ward_Eight',NULL,2,'Whiskey',0.75,'Lemon_Juice',0.75,'Orange_Juice',0.02,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Washington_Apple_Martini',NULL,1,'Whiskey',1,'Sour_Apple_Schnapps',1,'Cranberry_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Yellow_Submarine',NULL,1.50,'Vodka',0.50,'White_Rum',0.50,'Banana_Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Zombie',NULL,1,'Light_Rum',1,'Dark_Rum',1,'Orange_Curacao_Liqueur',1.50,'Orange_Juice',1.50,'Passion_Fruit_Puree',0.50,'Lemon_Juice',0.50,'Lime_Juice',0.25,'Grenadine',0.06,'Angostura_Bitters');



// doesn't work because it uses fractions not floats //
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Alabama_Slammer',NULL,'1','Southern Comfort','1','Amaretto','1','Sloe_Gin','2','Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Americano',NULL,'3/2','Campari','3/2','Sweet_Vermouth','3/2','Soda_Water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Anejo_Highball',NULL,'3/2','Rum','1/2','Orange_Cruacao','1/2','Lime_Juice','2','Ginger_Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Bacardi_Cocktail',NULL,'2','Light_Rum','1/2','Lime_Juice','1/2','Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Bay_Breeze',NULL,'2','Vodka','3','Cranberry_Juice','3','Pineapple_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Bees_Knees',NULL,'2','Gin','3/4','Honey_Syrup','1/2','Lemon_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Campari_and_Soda',NULL,'2','Campary','6','Soda_Water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Cantarito',NULL,'3/2','Tequila','1/2','Lime_Juice','1/2','Lemon_Juice','1/2','Orange_Juice','4','Grapefruit_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Cape_Cod',NULL,'3','Cranberry_Juice','2','Vodka',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Dark_and_Stormy',NULL,'1/2','Dark_Rum','3','Ginger_Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Dry_Martini',NULL,'5/2','Gin','1/2','Dry_Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Dubonnet_Cocktail',NULL,'3/2','Gin','3/4','Dubonnet_Rogue',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Easter_Bunny',NULL,'3/2','Creme_De_Cacao','1/2','Vodka','1/6','Chocolate_Syruop','1/6','Cherry_Brandy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Electric_Iced_Tea',NULL,'1/2','Vodka','1/2','Light_Rum','1/2','Tequila','1/2','Gin','1/2','Blue_Curacao','1','Sour_Mix','1','Lemon_Lime_Soda',NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('El_Diablo',NULL,'3/2','Reposado_tequila','1/2','Creme_De_Cassis','1/2','Lime_Juice','6','Ginger Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('French_75',NULL,'3/2','Gin','1/6','Syrup','1/2','Fresh_Lemon_Juice','4','Champagne',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('French_Pear_Martini',NULL,'3/2','Elderflower_Liqueur','3/2','Pear_Vodka','1','Champagne',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Friar_Tuck_Cocktails',NULL,'1','Frangelico','1','Dark_Creme_De_Cacao','2','Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Gibson_Cocktail',NULL,'5/2','Gin','1/2','Dry_Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Gimlet',ARRAY [],'2','Gin','3/4','Lime_Cordial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Gir_Scout_Cookie_Cocktail',NULL,'1/2','Coffee-Liqueur','1/2','Irish_Cream_Liqueur','1/2','Peppermint_Schnapps',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Hairy_Navel_Cocktail',NULL,'1','Vodka','1','Peach_Schnapps','8','Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Harvey Wallbanger Cocktail',NULL,'3/2','Vodka','4','Orange_Juice','½','Galliano_L’Autentico',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Hawaiian_Iced_tea',],'1/2','Vodka','1/2','Light_Rum','1/2','Tequila','½','Gin','1/2','Triple_Sec','1','Sour_Mix','2','Pineapple_Juice',NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Irish_Slammer',NULL,'3/4','Irish_Cream_Liqueur','3/4','Irish_Whiskey','8','Guinness',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Irish_Coffee',NULL,'3/2','Brown_Sugar','4','Coffee','3/2','Irish_Whiskey','1','Heavy_Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Irish_Cactus',NULL,'2','Irish_Cream_Liqueur','1','Tequila',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Jack_O_Lantern',NULL,'3/2','Cognac','1/2','Orange_Liqueur','1','Orange_Juice','2','Ginger_Ale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Jack_Rose',NULL,'5/2','AppleJack','3/4','Lemon_Juice','1/2','Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Jalisco_High_Tea_Tequila',NULL,'3/2','Tequila','3/2','Lemon_Verbena_Tea','1/4','Cherry_Liqueur','1/2','Simple_Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Kentucky_Coffee',NULL,'1','Bourbon_Whiskey','1/2','Honey_Liqueur','6','Hot_Coffee',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Key_Lime_Pie_Martini',NULL,'3/2','Vanila_Vodka','1/2','Triple_Sec_Orange_Liqueur','1','Pineapple_Juice','1/2','Lime_Cordial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('KnickerBocker',NULL,'5/2','Rum','1/2','Raspberry-Syrup','1','Orange_Curacao','1/2','Lime_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Lavender_Martini',NULL,'2','gin','1/2','Dry_Vermouth','½','Lavender_Simple _Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Long_Beached_Iced_Tea',NULL,'1/2','Vodka','1/2','Light_Rum','1/2','Tequila','1/2','Gin','1/2','Triple_Sec','1','Sour_Mix','2','Cranberrry_Juice',NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Lady_Liberty',NULL,'2','Rum','1','Orgeat_syrup','1/4','Maraschino_Liqueur','1/4','Green_Chartreuse','1','Lime_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Madras',NULL,'3/2','Vodka','3','Cranberry_Juice','1','Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Mai_Tai',NULL,'1','Rhum_Agricole','1','Dark_Rum','1','Lime_Juice','1/2','Orange_Curacao','1/2','Orgeat_syrup','1/4','Simple_Syrup',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Metropolitan',NULL,'2','Brandy','1','Sweet_Vermouth','1/10','Simple_Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Napoleon',NULL,'2','Gin','1/2','Orange_Liqueur','½','Debonnet_Rouge',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Nevada_Cocktail',NULL,'3/2','Light_Rum','3/2','Grapefruit_Juice','1','Lime_Juice','1/3','Superfine_Sugar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Nightcap',NULL,'1','Brandy','1','Anisettem1','1','Curacao_Liqueur','1','Egg_Yolk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Orange_Blossom_Cocktail',NULL,'3/4','Gin','3/4','Sweet_Vermouth','3/4','Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Orange_Martini',NULL,'2','Gin','1/2','Triple_sec','1/2','Dry_Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('O_Sole_Mio',NULL,'3/2','Antica-Orange_and_Mango','1/2','Lemon_Juice','2','Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Painkiller',NULL,'2','Rum','4','Pineapple_Juice','1','Orange_Juice','1','Cream_of_Coconut',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Paloma',NULL,'2','tequila','1/3','Lime_juice','4','Grapefruit_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Peppermint_Patty',NULL,'2','Chocolate_Vodka','1/2','Peppermint_Schnapps','3/4','Cream_Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Raspberry_Gimlet_Shooter',NULL,'3/2','Vodka','1/2','Lime_Juice','1/32','Black_Raspberry_Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Red_Beer',NULL,'2','Tomato_Juice','12','Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Robert_Burns',NULL,'2','Scotch_Whisky','3/4','Sweet_Vermouth','1/32','Orange_bitters','1/32','Absinthe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Sake_Martini',NULL,'5/2','Gin','1/2','Sake',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Shirley_Temple',NULL,'1/4','Grenadine','3','Lemon-Lime_Soda','3','Ginger_Ale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Scoth_Sour',NULL,'3/2','Scotch_Whiskey','3/4','Lemon_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Tequini',NULL,'5/2','Tequila','1/2','Dry_Vermouth','1/32','Angousta_Bitters',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Talking_Monkey',NULL,'1','Chocolate_Vodka','1/32','Espresso_Vodka','1','Banana_Liqueur','1/32','Coffee_Liqueur','1','Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Tornado',NULL,'1','Whiskey','1','Vodka','1','Rum','1','Tequila','2','Cola','1/6','Sugar',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Vermouth_Cassis',NULL,'5/2','Dry_Vermouth','3/4','Creme_De_Cassis','3','Club_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Vieux_Carre',NULL,'3/4','Rye_Whiskey','3/4','Cognac','3/4','Sweet_Vermouth','1/2','Benedictine_Liqueur','1/16','Peychaud’s_bitters','1/16','Aromatic_Bitters',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Vampires_Kiss',NULL,'3/2','Melon_Liqueur','1','Orange_Vodk','2','Pineapple_Juice','1/2','Cream','1/32','Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Waldorf',NULL,'2','Rye_Whiskey','3/4','Sweet_Vermouth','1/4','Absinthe','1/16','Bitters',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Ward_Eight',NULL,'2','Whiskey','3/4','Lemon_Juice','3/4','Orange_Juice','1/32','Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Washington_Apple_Martini',NULL,'1','Whiskey','1','Sour_Apple_Schnapps','1','Cranberry_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Yellow_Submarine',NULL,'3/2','Vodka','1/2','White_Rum','1/2','Banana_Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Zombie',NULL,'1','Light_Rum','1','Dark_Rum','1','Orange_Curacao_Liqueur','3/2','Orange_Juice','3/2','Passion_Fruit_Puree','1/2','Lemon_Juice','1/2','Lime_Juice','1/4','Grenadine','1/16','Angostura_Bitters');
