
<<<<<<< HEAD
DROP TABLE drinks CASCADE;
=======
CREATE TABLE IF NOT EXISTS categories(
  id SERIAL PRIMARY KEY,       /* Unique identifier for each player (it's possible multiple players have the same name/similiar information) */
  name VARCHAR(50) NOT NULL,   /* The player's first & last name */
  description TEXT NULL,             /* FSH - Freshman, SPH - Sophomore, JNR - Junior, SNR - Senior */
  img_src VARCHAR(200)         /* This is a file path (absolute or relative), that locates the drink image */
);

>>>>>>> 37a2698f9f34ffd27840bf8c718cc60fdbaab1ff

CREATE TABLE IF NOT EXISTS drinks(
   drink_id SERIAL PRIMARY KEY
  ,drink_name        VARCHAR(26) NOT NULL
  ,category          INT NULL
  ,quantiry_one_oz   FLOAT NULL
  ,ingredient_one    VARCHAR(23) NULL
  ,quantity_two_oz   FLOAT NULL 
  ,ingredient_two    VARCHAR(25) NULL
  ,quantity_three_oz FLOAT NULL
  ,ingredient_three  VARCHAR(23) NULL
  ,quantity_four_oz  FLOAT NULL
  ,ingredient_four   VARCHAR(19) NULL
  ,quantity_five_oz  FLOAT NULL
  ,ingredient_five   VARCHAR(19) NULL
  ,quantity_six_oz   FLOAT NULL
  ,ingredient_six    VARCHAR(16) NULL
  ,quantity_seven_oz FLOAT NULL
  ,ingredient_seven  VARCHAR(16) NULL
  ,quantity_eight_oz FLOAT NULL
  ,ingredient_eight  VARCHAR(9) NULL
  ,quantity_nine_oz  FLOAT NULL
  ,ingredient_nine   VARCHAR(17) NULL
);

<<<<<<< HEAD
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine)
VALUES('Alabama_Slammer',NULL,1,'Southern Comfort',1,'Amaretto',1,'Sloe_Gin',2,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Americano',NULL,1.50,'Campari',1.50,'Sweet_Vermouth',1.50,'Soda_Water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Anejo_Highball',NULL,1.50,'Rum',0.50,'Orange_Cruacao',0.50,'Lime_Juice',2,'Ginger_Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bacardi_Cocktail',NULL,2,'Light_Rum',0.50,'Lime_Juice',0.50,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bay_Breeze',NULL,2,'Vodka',3,'Cranberry_Juice',3,'Pineapple_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bees_Knees',NULL,2,'Gin',0.75,'Honey_Syrup',0.50,'Lemon_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Campari_and_Soda',NULL,2,'Campary',6,'Soda_Water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cantarito',NULL,1.50,'Tequila',0.50,'Lime_Juice',0.50,'Lemon_Juice',0.50,'Orange_Juice',4,'Grapefruit_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cape_Cod',NULL,3,'Cranberry_Juice',2,'Vodka',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dark_and_Stormy',NULL,0.50,'Dark_Rum',3,'Ginger_Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dry_Martini',NULL,2.50,'Gin',0.50,'Dry_Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Dubonnet_Cocktail',NULL,1.50,'Gin',0.75,'Dubonnet_Rogue',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Easter_Bunny',NULL,1.50,'Creme_De_Cacao',0.50,'Vodka',0.16,'Chocolate_Syruop',0.16,'Cherry_Brandy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Electric_Iced_Tea',NULL,0.50,'Vodka',0.50,'Light_Rum',0.50,'Tequila',0.50,'Gin',0.50,'Blue_Curacao',1,'Sour_Mix',1,'Lemon_Lime_Soda',NULL,NULL,NULL,NULL),
('El_Diablo',NULL,1.50,'Reposado_tequila',0.50,'Creme_De_Cassis',0.50,'Lime_Juice',6,'Ginger Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('French_75',NULL,1.50,'Gin',0.16,'Syrup',0.50,'Fresh_Lemon_Juice',4,'Champagne',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('French_Pear_Martini',NULL,1.50,'Elderflower_Liqueur',1.50,'Pear_Vodka',1,'Champagne',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Friar_Tuck_Cocktails',NULL,1,'Frangelico',1,'Dark_Creme_De_Cacao',2,'Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gibson_Cocktail',NULL,2.50,'Gin',0.50,'Dry_Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gimlet',NULL,2,'Gin',0.75,'Lime_Cordial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Gir_Scout_Cookie_Cocktail',NULL,0.50,'Coffee-Liqueur',0.50,'Irish_Cream_Liqueur',0.50,'Peppermint_Schnapps',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hairy_Navel_Cocktail',NULL,1,'Vodka',1,'Peach_Schnapps',8,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Harvey Wallbanger Cocktail',NULL,1.50,'Vodka',4,'Orange_Juice',0.50,'Galliano_L’Autentico',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hawaiian_Iced_tea',NULL,0.50,'Vodka',0.50,'Light_Rum',0.50,'Tequila',0.50,'Gin',0.50,'Triple_Sec',1,'Sour_Mix',2,'Pineapple_Juice',NULL,NULL,NULL,NULL),
('Irish_Slammer',NULL,0.75,'Irish_Cream_Liqueur',0.75,'Irish_Whiskey',8,'Guinness',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Irish_Coffee',NULL,1.50,'Brown_Sugar',4,'Coffee',1.50,'Irish_Whiskey',1,'Heavy_Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Irish_Cactus',NULL,2,'Irish_Cream_Liqueur',1,'Tequila',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jack_O_Lantern',NULL,1.50,'Cognac',0.50,'Orange_Liqueur',1,'Orange_Juice',2,'Ginger_Ale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jack_Rose',NULL,2.50,'AppleJack',0.75,'Lemon_Juice',0.50,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Jalisco_High_Tea_Tequila',NULL,1.50,'Tequila',1.50,'Lemon_Verbena_Tea',0.25,'Cherry_Liqueur',0.50,'Simple_Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Kentucky_Coffee',NULL,1,'Bourbon_Whiskey',0.50,'Honey_Liqueur',6,'Hot_Coffee',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Key_Lime_Pie_Martini',NULL,1.50,'Vanila_Vodka',0.50,'Triple_Sec_Orange_Liqueur',1,'Pineapple_Juice',0.50,'Lime_Cordial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('KnickerBocker',NULL,2.50,'Rum',0.50,'Raspberry-Syrup',1,'Orange_Curacao',0.50,'Lime_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Lavender_Martini',NULL,2,'gin',0.50,'Dry_Vermouth',0.50,'Lavender_Simple _Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Long_Beached_Iced_Tea',NULL,0.50,'Vodka',0.50,'Light_Rum',0.50,'Tequila',0.50,'Gin',0.50,'Triple_Sec',1,'Sour_Mix',2,'Cranberrry_Juice',NULL,NULL,NULL,NULL),
('Lady_Liberty',NULL,2,'Rum',1,'Orgeat_syrup',0.25,'Maraschino_Liqueur',0.25,'Green_Chartreuse',1,'Lime_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Madras',NULL,1.50,'Vodka',3,'Cranberry_Juice',1,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Mai_Tai',NULL,1,'Rhum_Agricole',1,'Dark_Rum',1,'Lime_Juice',0.50,'Orange_Curacao',0.50,'Orgeat_syrup',0.25,'Simple_Syrup',NULL,NULL,NULL,NULL,NULL,NULL),
('Metropolitan',NULL,2,'Brandy',1,'Sweet_Vermouth',0.10,'Simple_Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Napoleon',NULL,2,'Gin',0.50,'Orange_Liqueur',0.50,'Debonnet_Rouge',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nevada_Cocktail',NULL,1.50,'Light_Rum',1.50,'Grapefruit_Juice',1,'Lime_Juice',0.33,'Superfine_Sugar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Nightcap',NULL,1,'Brandy',1,'Anisettem1',1.00,'Curacao_Liqueur',1.00,'Egg_Yolk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Orange_Blossom_Cocktail',NULL,0.75,'Gin',0.75,'Sweet_Vermouth',0.75,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Orange_Martini',NULL,2,'Gin',0.50,'Triple_sec',0.50,'Dry_Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('O_Sole_Mio',NULL,1.50,'Antica-Orange_and_Mango',0.50,'Lemon_Juice',2,'Orange_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Painkiller',NULL,2,'Rum',4,'Pineapple_Juice',1,'Orange_Juice',1,'Cream_of_Coconut',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Paloma',NULL,2,'tequila',0.33,'Lime_juice',4,'Grapefruit_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Peppermint_Patty',NULL,2,'Chocolate_Vodka',0.50,'Peppermint_Schnapps',0.75,'Cream_Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Raspberry_Gimlet_Shooter',NULL,1.50,'Vodka',0.50,'Lime_Juice',0.03,'Black_Raspberry_Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Red_Beer',NULL,2,'Tomato_Juice',12,'Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Robert_Burns',NULL,2,'Scotch_Whisky',0.75,'Sweet_Vermouth',0.03,'Orange_bitters',0.03,'Absinthe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Sake_Martini',NULL,2.50,'Gin',0.50,'Sake',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Shirley_Temple',NULL,0.25,'Grenadine',3,'Lemon-Lime_Soda',3.00,'Ginger_Ale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Scoth_Sour',NULL,1.50,'Scotch_Whiskey',0.75,'Lemon_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tequini',NULL,2.50,'Tequila',0.50,'Dry_Vermouth',0.03,'Angousta_Bitters',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Talking_Monkey',NULL,1,'Chocolate_Vodka',0.03,'Espresso_Vodka',1,'Banana_Liqueur',0.03,'Coffee_Liqueur',1,'Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tornado',NULL,1,'Whiskey',1,'Vodka',1,'Rum',1,'Tequila',2,'Cola',0.06,'Sugar',NULL,NULL,NULL,NULL,NULL,NULL),
('Vermouth_Cassis',NULL,2.50,'Dry_Vermouth',0.75,'Creme_De_Cassis',3,'Club_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Vieux_Carre',NULL,0.75,'Rye_Whiskey',0.75,'Cognac',0.75,'Sweet_Vermouth',0.50,'Benedictine_Liqueur',.06,'Peychaud’s_bitters',.06,'Aromatic_Bitters',NULL,NULL,NULL,NULL,NULL,NULL),
('Vampires_Kiss',NULL,1.50,'Melon_Liqueur',1,'Orange_Vodk',2,'Pineapple_Juice',0.50,'Cream',0.03,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Waldorf',NULL,2,'Rye_Whiskey',0.75,'Sweet_Vermouth',0.25,'Absinthe',0.06,'Bitters',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Ward_Eight',NULL,2,'Whiskey',0.75,'Lemon_Juice',0.75,'Orange_Juice',0.02,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Washington_Apple_Martini',NULL,1,'Whiskey',1,'Sour_Apple_Schnapps',1,'Cranberry_Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Yellow_Submarine',NULL,1.50,'Vodka',0.50,'White_Rum',0.50,'Banana_Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Zombie',NULL,1,'Light_Rum',1,'Dark_Rum',1,'Orange_Curacao_Liqueur',1.50,'Orange_Juice',1.50,'Passion_Fruit_Puree',0.50,'Lemon_Juice',0.50,'Lime_Juice',0.25,'Grenadine',0.06,'Angostura_Bitters')
;

=======

INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Alabama Slammer',NULL,1,'Southern Comfort',1,'Amaretto',1,'Sloe Gin',2,'Orange Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Americano',NULL,1.50,'Campari',1.50,'Sweet Vermouth',1.50,'Soda Water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Anejo Highball',NULL,1.50,'Rum',0.50,'Orange Cruacao',0.50,'Lime Juice',2,'Ginger Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Bacardi Cocktail',NULL,2,'Light Rum',0.50,'Lime Juice',0.50,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Bay Breeze',NULL,2,'Vodka',3,'Cranberry Juice',3,'Pineapple Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Bees Knees',NULL,2,'Gin',0.75,'Honey Syrup',0.50,'Lemon Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Campari and Soda',NULL,2,'Campary',6,'Soda Water',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Cantarito',NULL,1.50,'Tequila',0.50,'Lime Juice',0.50,' Lemon Juice',0.50,'Orange Juice',4,'Grapefruit_Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Cape Cod',NULL,3,'Cranberry Juice',2,'Vodka',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Dark and Stormy',NULL,0.50,'Dark Rum',3,'Ginger Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Dry Martini',NULL,2.50,'Gin',0.50,'Dry Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Dubonnet Cocktail',NULL,1.50,'Gin',0.75,'Dubonnet Rogue',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Easter Bunny',NULL,1.50,'Creme De Cacao',0.50,'Vodka',0.16,'Chocolate Syruop',0.16,'Cherry Brandy',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Electric Iced Tea',NULL,0.50,'Vodka',0.50,'Light Rum',0.50,'Tequila',0.50,'Gin',0.50,'Blue Curacao',1,'Sour Mix',1,'Lemon Lime Soda',NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('El Diablo',NULL,1.50,'Reposado tequila',0.50,'Creme De Cassis',0.50,'Lime Juice',6,'Ginger Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('French 75',NULL,1.50,'Gin',0.16,'Syrup',0.50,'Fresh Lemon Juice',4,'Champagne',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('French Pear Martini',NULL,1.50,'Elderflower Liqueur',1.50,'Pear Vodka',1,'Champagne',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Friar Tuck Cocktails',NULL,1,'Frangelico',1,'Dark Creme De Cacao',2,'Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Gibson Cocktail',NULL,2.50,'Gin',0.50,'Dry Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Gimlet',NULL,2,'Gin',0.75,'Lime Cordial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Girl Scout Cookie Cocktail',NULL,0.50,'Coffee-Liqueur',0.50,'Irish Cream Liqueur',0.50,'Peppermint Schnapps',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Hairy Navel Cocktail',NULL,1,'Vodka',1,'Peach Schnapps',8,'Orange Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Harvey Wallbanger Cocktail',NULL,1.50,'Vodka',4,'Orange Juice',0.50,'Galliano L’Autentico',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Hawaiian Iced tea',NULL,0.50,'Vodka',0.50,'Light Rum',0.50,'Tequila',0.50,'Gin',0.50,'Triple Sec',1,'Sour Mix',2,'Pineapple Juice',NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Irish Slammer',NULL,0.75,'Irish Cream Liqueur',0.75,'Irish Whiskey',8,'Guinness',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Irish Coffee',NULL,1.50,'Brown Sugar',4,'Coffee',1.50,'Irish Whiskey',1,'Heavy Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Irish Cactus',NULL,2,'Irish Cream Liqueur',1,'Tequila',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Jack O Lantern',NULL,1.50,'Cognac',0.50,'Orange Liqueur',1,'Orange Juice',2,'Ginger Ale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Jack Rose',NULL,2.50,'AppleJack',0.75,' Lemon Juice',0.50,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Jalisco High Tea Tequila',NULL,1.50,'Tequila',1.50,'Lemon Verbena Tea',0.25,'Cherry Liqueur',0.50,'Simple Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Kentucky Coffee',NULL,1,'Bourbon Whiskey',0.50,'Honey Liqueur',6,'Hot Coffee',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Key Lime Pie Martini',NULL,1.50,'Vanila Vodka',0.50,'Triple Sec Orange Liqueur',1,'Pineapple Juice',0.50,'Lime Cordial',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('KnickerBocker',NULL,2.50,'Rum',0.50,'Raspberry-Syrup',1,'Orange Curacao',0.50,'Lime Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Lavender Martini',NULL,2,'gin',0.50,'Dry Vermouth',0.50,'Lavender Simple  Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Long Beached Iced Tea',NULL,0.50,'Vodka',0.50,'Light Rum',0.50,'Tequila',0.50,'Gin',0.50,'Triple Sec',1,'Sour Mix',2,'Cranberrry Juice',NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Lady Liberty',NULL,2,'Rum',1,'Orgeat syrup',0.25,'Maraschino Liqueur',0.25,'Green Chartreuse',1,'Lime Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Madras',NULL,1.50,'Vodka',3,'Cranberry Juice',1,'Orange Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Mai Tai',NULL,1,'Rhum Agricole',1,'Dark Rum',1,'Lime Juice',0.50,'Orange Curacao',0.50,'Orgeat syrup',0.25,'Simple Syrup',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Metropolitan',NULL,2,'Brandy',1,'Sweet Vermouth',0.10,'Simple Syrup',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Napoleon',NULL,2,'Gin',0.50,'Orange Liqueur',0.50,'Debonnet Rouge',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Nevada Cocktail',NULL,1.50,'Light Rum',1.50,'Grapefruit Juice',1,'Lime Juice',0.33,'Superfine Sugar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Nightcap',NULL,1,'Brandy',1,'Anisettem1',1.00,'Curacao Liqueur',1.00,'Egg Yolk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Orange Blossom Cocktail',NULL,0.75,'Gin',0.75,'Sweet Vermouth',0.75,'Orange Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Orange Martini',NULL,2,'Gin',0.50,'Triple sec',0.50,'Dry Vermouth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('O Sole Mio',NULL,1.50,'Antica-Orange and Mango',0.50,' Lemon Juice',2,'Orange Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Painkiller',NULL,2,'Rum',4,'Pineapple Juice',1,'Orange Juice',1,'Cream of Coconut',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Paloma',NULL,2,'tequila',0.33,'Lime juice',4,'Grapefruit Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Peppermint Patty',NULL,2,'Chocolate Vodka',0.50,'Peppermint Schnapps',0.75,'Cream Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Raspberry Gimlet Shooter',NULL,1.50,'Vodka',0.50,'Lime Juice',0.03,'Black Raspberry Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Red Beer',NULL,2,'Tomato Juice',12,'Beer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Robert Burns',NULL,2,'Scotch Whisky',0.75,'Sweet Vermouth',0.03,'Orange bitters',0.03,'Absinthe',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Sake Martini',NULL,2.50,'Gin',0.50,'Sake',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Shirley Temple',NULL,0.25,'Grenadine',3,'Lemon-Lime Soda',3.00,'Ginger Ale',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Scoth Sour',NULL,1.50,'Scotch Whiskey',0.75,' Lemon Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Tequini',NULL,2.50,'Tequila',0.50,'Dry Vermouth',0.03,'Angousta Bitters',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Talking Monkey',NULL,1,'Chocolate Vodka',0.03,'Espresso Vodka',1,'Banana Liqueur',0.03,'Coffee Liqueur',1,'Cream',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Tornado',NULL,1,'Whiskey',1,'Vodka',1,'Rum',1,'Tequila',2,'Cola',0.06,'Sugar',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Vermouth Cassis',NULL,2.50,'Dry Vermouth',0.75,'Creme De Cassis',3,'Club Soda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Vieux Carre',NULL,0.75,'Rye Whiskey',0.75,'Cognac',0.75,'Sweet Vermouth',0.50,'Benedictine Liqueur',.06,'Peychaud’s bitters',.06,'Aromatic Bitters',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Vampires Kiss',NULL,1.50,'Melon Liqueur',1,'Orange Vodka',2,'Pineapple Juice',0.50,'Cream',0.03,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Waldorf',NULL,2,'Rye Whiskey',0.75,'Sweet Vermouth',0.25,'Absinthe',0.06,'Bitters',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Ward Eight',NULL,2,'Whiskey',0.75,' Lemon Juice',0.75,'Orange Juice',0.02,'Grenadine',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Washington Apple Martini',NULL,1,'Whiskey',1,'Sour Apple Schnapps',1,'Cranberry Juice',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Yellow Submarine',NULL,1.50,'Vodka',0.50,'White Rum',0.50,'Banana Liqueur',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO drinks(drink_name,category,quantiry_one_oz,ingredient_one,quantity_two_oz,ingredient_two,quantity_three_oz,ingredient_three,quantity_four_oz,ingredient_four,quantity_five_oz,ingredient_five,quantity_six_oz,ingredient_six,quantity_seven_oz,ingredient_seven,quantity_eight_oz,ingredient_eight,quantity_nine_oz,ingredient_nine) VALUES ('Zombie',NULL,1,'Light Rum',1,'Dark Rum',1,'Orange Curacao Liqueur',1.50,'Orange Juice',1.50,'Passion Fruit Puree',0.50,' Lemon Juice',0.50,'Lime Juice',0.25,'Grenadine',0.06,'Angostura Bitters');
>>>>>>> 37a2698f9f34ffd27840bf8c718cc60fdbaab1ff



